declare const randomJSON = "{\n    {\n        \"name\": \"Muhammad Ishaq\",\n        \"gender\": \"Male\",\n        \"age\": 23,\n        \"address\": null,\n        \"phoneNumber\": [\n            { \"type\": \"personal\", \"number\": \"116263747\" }\n        ]\n    }";
declare const randomJSON2 = "{\n\t\"id\": \"0001\",\n\t\"type\": \"donut\",\n\t\"name\": \"Cake\",\n\t\"ppu\": 0.55,\n\t\"batters\":\n\t\t{\n\t\t\t\"batter\":\n\t\t\t\t[\n\t\t\t\t\t{ \"id\": \"1001\", \"type\": \"Regular\" },\n\t\t\t\t\t{ \"id\": \"1002\", \"type\": \"Chocolate\" },\n\t\t\t\t\t{ \"id\": \"1003\", \"type\": \"Blueberry\" },\n\t\t\t\t\t{ \"id\": \"1004\", \"type\": \"Devil's Food\" }\n\t\t\t\t]\n\t\t},\n\t\"topping\":\n\t\t[\n\t\t\t{ \"id\": \"5001\", \"type\": \"None\" },\n\t\t\t{ \"id\": \"5002\", \"type\": \"Glazed\" },\n\t\t\t{ \"id\": \"5005\", \"type\": \"Sugar\" },\n\t\t\t{ \"id\": \"5007\", \"type\": \"Powdered Sugar\" },\n\t\t\t{ \"id\": \"5006\", \"type\": \"Chocolate with Sprinkles\" },\n\t\t\t{ \"id\": \"5003\", \"type\": \"Chocolate\" },\n\t\t\t{ \"id\": \"5004\", \"type\": \"Maple\" }\n\t\t]\n}";
declare const randomJSON4 = "{\n    \"ancestor\":{\n        \"menu\": {\n            \"header\": \"SVG Viewer\",\n            \"mikhail\" : \"zerafa\",\n            \"items\": [\n                {\"id\": \"Open\"},\n                {\"id\": \"OpenNew\", \"label\": \"Open New\"},\n                null,\n                {\"id\": \"ZoomIn\", \"label\": \"Zoom In\"},\n                {\"id\": \"ZoomOut\", \"label\": \"Zoom Out\"},\n                {\"id\": \"OriginalView\", \"label\": \"Original View\"},\n                null,\n                {\"id\": \"Quality\"},\n                {\"id\": \"Pause\"},\n                {\"id\": \"Mute\"},\n                null,\n                {\"id\": \"Find\", \"label\": \"Find...\"},\n                {\"id\": \"FindAgain\", \"label\": \"Find Again\"},\n                {\"id\": \"Copy\"},\n                {\"id\": \"CopyAgain\", \"label\": \"Copy Again\"},\n                {\"id\": \"CopySVG\", \"label\": \"Copy SVG\"},\n                {\"id\": \"ViewSVG\", \"label\": \"View SVG\"},\n                {\"id\": \"ViewSource\", \"label\": \"View Source\"},\n                {\"id\": \"SaveAs\", \"label\": \"Save As\"},\n                null,\n                {\"id\": \"Help\"},\n                {\"id\": \"About\", \"label\": \"About Adobe CVG Viewer...\"}\n            ]\n        },\n        \"menu2\": {\n            \"header\" : \"test header\"\n        }\n    }\n}";
declare const randomJSON5 = "{\n    \"items\": [\n        \"first\", \"second\", \"third\", \"forth\"\n    ]\n}\n";
declare const randomJSON6: {
    items: number[];
};
declare const randomJSON7 = "{\n        \"siteInfo\": {\n\t\"name\": \"blogger\",\n\t\"users\": [\n\t\t[ \"admins\", \"1\", \"2\" , \"3\"],\n\t\t[ \"editors\", \"4\", \"5\" , \"6\"]\n\t]\n}}\n";
declare const randomJSON8 = "{\n    \"problems\": [{\n        \"Diabetes\":[{\n            \"medications\":[{\n                \"medicationsClasses\":[{\n                    \"className\":[{\n                        \"associatedDrug\":[{\n                            \"name\":\"asprin\",\n                            \"dose\":\"\",\n                            \"strength\":\"500 mg\"\n                        }],\n                        \"associatedDrug#2\":[{\n                            \"name\":\"somethingElse\",\n                            \"dose\":\"\",\n                            \"strength\":\"500 mg\"\n                        }]\n                    }],\n                    \"className2\":[{\n                        \"associatedDrug\":[{\n                            \"name\":\"asprin\",\n                            \"dose\":\"\",\n                            \"strength\":\"500 mg\"\n                        }],\n                        \"associatedDrug#2\":[{\n                            \"name\":\"somethingElse\",\n                            \"dose\":\"\",\n                            \"strength\":\"500 mg\"\n                        }]\n                    }]\n                }]\n            }],\n            \"labs\":[{\n                \"missing_field\": \"missing_value\"\n            }]\n        }],\n        \"Asthma\": [{}]\n    }]}\n";
declare const randomJSON9 = "{\n    \"data\": [\n        {\n            \"MainId\": 1111,\n            \"firstName\": \"Sherlock\",\n            \"lastName\": \"Homes\",\n            \"categories\": [\n                {\n                    \"CategoryID\": 1,\n                    \"CategoryName\": \"Example\"\n                }\n            ]\n        },\n        {\n            \"MainId\": 122,\n            \"firstName\": \"James\",\n            \"lastName\": \"Watson\",\n            \"categories\": [\n                {\n                    \"CategoryID\": 2,\n                    \"CategoryName\": \"Example2\"\n                }\n            ]\n        }\n    ],\n    \"messages\": [], \n    \"success\": true \n}\n";
declare const tempJson: string;
export { randomJSON, randomJSON2, randomJSON4, randomJSON5, randomJSON6, randomJSON7, randomJSON8, randomJSON9, tempJson };
//# sourceMappingURL=mock.d.ts.map